# config_data.py
import os # <--- ADDED THIS

INTERNAL_HOURLY_RATES = {
    "Default": 100,
    "Strategy & Concept": 100,
    "xyz....": 100,
    "xyz..": 60 # Here the service areas & correct hourly raties shuld be inputtet
}

TYPICAL_SERVICE_AREAS = list(INTERNAL_HOURLY_RATES.keys())

# --- LLM MODELS ---
LLM_MODEL_CHAT = "gpt-4.1"
LLM_MODEL_JSON_DRAFT = "gpt-4.1"

# --- DATA DIRECTORIES ---
DATA_DIR = "data/offers_knowledge_base"

# --- EXTERNAL API CONFIGURATIONS ---
# For OpenRouter/Perplexity Integration
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
PERPLEXITY_MODEL_NAME = "perplexity/sonar-pro" # QUALITY: perplexity/sonar-deep-research | QUICK: perplexity/sonar-pro


def calculate_position_price(service_area: str, estimated_hours: float) -> dict:
    print(f"\n--- Function: calculate_position_price called ---")
    print(f"Service Area: {service_area}, Estimated Hours: {estimated_hours}")

    if not isinstance(estimated_hours, (int, float)) or estimated_hours <= 0:
        print("Error: Estimated hours must be a positive number.")
        return {"error": "Estimated hours must be a positive number."}

    hourly_rate = INTERNAL_HOURLY_RATES.get(service_area)
    service_area_used = service_area

    if hourly_rate is None:
        print(f"Warning: Service area '{service_area}' not found. Using 'Default' rate.")
        hourly_rate = INTERNAL_HOURLY_RATES.get("Default") 
        service_area_used = "Default"
        
    calculated_price = round(hourly_rate * estimated_hours, 2)
    print(f"Calculated Price: {calculated_price} CHF (Rate: {hourly_rate} CHF/hr)")
    
    return {
        "calculated_price_chf": calculated_price,
        "hourly_rate_chf": hourly_rate,
        "service_area_used": service_area_used,
        "estimated_hours_input": estimated_hours
    }

# (calculate_position_price_tool_description can remain here if you plan to use OpenAI function calling directly later)


# --- BEXIO API CONFIGURATION ---
BEXIO_API_TOKEN = os.getenv("BEXIO_API_TOKEN", "YOUR_BEXIO_API_TOKEN_PLACEHOLDER_IN_CONFIG") # Actual token should be in .env
BEXIO_API_URL = "https://api.bexio.com/2.0/kb_offer" # POST to this for creating offers

# Default values for Bexio payload.
# IMPORTANT: Review and update these values to match your specific Bexio setup,
# especially IDs for contacts, accounts, taxes, units, etc.
# These can be found by using the Bexio API (e.g., GET /2.0/users, GET /2.0/contacts, GET /2.0/taxes)
# or by looking them up in your Bexio web interface (often visible in URLs when editing items).

BEXIO_USER_ID = 30                       # ID of the Bexio user / 30 is Omar
BEXIO_CONTACT_ID = 2                     # ID of the Bexio contact (client) 2 = Sidekicks
BEXIO_LOGOPAPER_ID = 1                  # ID of the logopaper to use
BEXIO_LANGUAGE_ID = 1                   # 1 for German, 2 for English
BEXIO_BANK_ACCOUNT_ID = 1               # ID of the bank account to show on the offer.
BEXIO_CURRENCY_ID = 1                   # 1 for CHF.
BEXIO_PAYMENT_TYPE_ID = None            # ID for payment terms None = default. 4 = '30 days net'.
BEXIO_MWST_TYPE = 0                     # VAT type: 0 = including taxes, 1 = excluding taxes, 2 = exempt from taxes.
BEXIO_MWST_IS_NET = True                # If mwst_type is 0 (inclusive):
                                        #   True = VAT will be added to the total (prices are net).
                                        #   False = VAT is included in the total (prices are gross).
BEXIO_SHOW_POSITION_TAXES = False       # Whether to show taxes per position on the PDF.
BEXIO_DOCUMENT_NR = None                # autogenerated if none
BEXIO_TEMPLATE_SLUG = None              # Slug of a specific offer template in Bexio. e.g., "angebot-standard-v2". None for default.

# For Positions:
BEXIO_UNIT_ID_HOURS = None              # ID for the unit "Hours" (or "Stunde"). Set to None or a different value for better display if needed.
BEXIO_ACCOUNT_ID_SERVICES = 274         # Revenue account ID for services (e.g., "Erlös Dienstleistungen").
BEXIO_TAX_ID_STANDARD = 67              # Tax ID for the standard VAT rate (e.g., 8.1%).
                                        # CRITICAL: Find this ID via Bexio API /3.0/taxes?types=sales_tax&scope=active
                                        # or in Bexio UI. An incorrect ID will cause errors.
                                        # Example: If you have a tax named "MWST 8.1% (Verkauf)" with ID 15, use 15.
